name: CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "FicsitRemoteMonitoring.uplugin"
      - "Content/**"
      - "Source/**"
  pull_request:
    branches:
      - "main"
      - "dev"
    paths:
      - "Content/**"
      - "Source/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cleanup
        run: Remove-Item C:\workspace\SatisfactoryModLoader -Recurse -Force -Confirm:$false -ErrorAction Ignore

      - uses: actions/checkout@v2
        with:
          path: FicsitRemoteMontioring

      - uses: actions/checkout@master
        with:
          repository: porisius/Disc-IT
          ref: refs/heads/master
          path: DiscIT

      - uses: actions/checkout@master
        with:
          repository: porisius/JSONQuery
          ref: refs/heads/master
          path: JSONQuery

      - uses: actions/checkout@master
        with:
          repository: porisius/ArduinoKit
          ref: refs/heads/main
          path: ArduinoKit

      - uses: actions/checkout@master
        with:
          repository: satisfactorymodding/SatisfactoryModLoader
          ref: refs/heads/dedicated-servers
          path: SatisfactoryModLoader

      - name: Copy Project to Workspace
        run: Copy-Item "$Env:GITHUB_WORKSPACE\\SatisfactoryModLoader" C:\workspace\ -Recurse -Force -Confirm:$false -ErrorAction Ignore

      - name: Copy FicsitRemoteMontioring to Project
        run: Copy-Item "$Env:GITHUB_WORKSPACE\\FicsitRemoteMontioring" C:\workspace\SatisfactoryModLoader\Mods\FicsitRemoteMonitoring -Recurse -Force -Confirm:$false -ErrorAction Ignore

      - name: Copy Non-Public Source Files to Mod
        run: Copy-Item C:\workspace\Source_Files\* C:\workspace\SatisfactoryModLoader\Mods\FicsitRemoteMonitoring\Source -Recurse -Force -Confirm:$false -ErrorAction Ignore

      - name: Copy ArduinoKit to Project
        run: Copy-Item "$Env:GITHUB_WORKSPACE\\ArduinoKit" C:\workspace\SatisfactoryModLoader\Mods\ArduinoKit -Recurse -Force -Confirm:$false -ErrorAction Ignore

      - name: Copy DiscIT to Project
        run: Copy-Item "$Env:GITHUB_WORKSPACE\\DiscIT" C:\workspace\SatisfactoryModLoader\Mods\DiscIT -Recurse -Force -Confirm:$false -ErrorAction Ignore

      - name: Copy JSONQuery to Project
        run: Copy-Item "$Env:GITHUB_WORKSPACE\\JSONQuery" C:\workspace\SatisfactoryModLoader\Mods\JSONQuery -Recurse -Force -Confirm:$false -ErrorAction Ignore

      - name: Extract WWise
        run: Expand-Archive -Path C:\workspace\WWise.zip -DestinationPath C:\workspace\SatisfactoryModLoader -Force

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Generate VS project files
        run: C:\workspace\ue\Engine\Build\BatchFiles\Build.bat -projectfiles -project='C:\workspace\SatisfactoryModLoader\FactoryGame.uproject' -game -rocket -progres

      - name: Build for Development Editor
        run: MSBuild.exe 'C:\workspace\SatisfactoryModLoader\FactoryGame.sln' /p:Configuration='Development Editor' /p:Platform='Win64' /t:'Games\FactoryGame' -m

      - name: Build for Shipping/Client
        run: MSBuild.exe 'C:\workspace\SatisfactoryModLoader\FactoryGame.sln' /p:Configuration='Shipping' /p:Platform='Win64' /t:'Games\FactoryGame' -m

      - name: Build for Win64 Dedicated Server
        run: MSBuild.exe 'C:\workspace\SatisfactoryModLoader\FactoryGame.sln' /p:Configuration='Shipping Server' /p:Platform='Win64' /t:'Games\FactoryGame' -m

      - name: Build for Linux Dedicated Server
        run: MSBuild.exe 'C:\workspace\SatisfactoryModLoader\FactoryGame.sln' /p:Configuration='Shipping Server' /p:Platform='Linux' /t:'Games\FactoryGame' -m

      - name: Package FicsitRemoteMonitoring Mod
        run: C:\workspace\ue\Engine\Build\BatchFiles\RunUAT.bat -ScriptsForProject='C:\workspace\SatisfactoryModLoader\FactoryGame.uproject' PackagePlugin -Project='C:\workspace\SatisfactoryModLoader\FactoryGame.uproject' -PluginName='FicsitRemoteMonitoring' -PluginTarget='Win64' -PluginTarget='Win64_Server' -PluginTarget='Linux_Server' -MergeArchive