name: Deploy

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Destination Repository
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: deploy-artifact
          path: . # Download the artifact to the current directory

      - name: Unzip and Replace Contents
        run: |
          unzip -o deploy-artifact
          rm -f deploy-artifact # Remove the zip file
