name: Deploy

on:
  workflow_run:
    workflows: ["Build and Release"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Destination Repository
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: ./www # Replace with the path to your "www" directory
